// Generated by CoffeeScript 1.10.0

/**
 * 下载google字体
 * @date 2015-12-22 09:45:19
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 */
'use strict';
var fs, getWoff2, md5, path, request;

path = require('path');

request = require('request');

md5 = require('./util').md5;

fs = require('fs-plus');

getWoff2 = function(css) {
  var woffMap;
  woffMap = [];
  String(css).split('url(').forEach(function(v) {
    if (v.indexOf(') format(') !== -1) {
      return woffMap.push(v.split(') format(')[0]);
    }
  });
  return woffMap;
};

module.exports = function(url, config) {
  var GFontsOutput;
  config.GFonts = config.GFonts || {
    output: path.join(config.basePath, 'style/gfonts')
  };
  GFontsOutput = config.GFonts.output;
  return request.get(url, function(err, res, body) {
    var done, downTotal, fileList, fileTotal, outDir;
    if (err) {
      return console.log(err);
    }
    outDir = path.join(GFontsOutput, md5(url).substring(0, 8));
    fs.makeTreeSync(outDir);
    fileList = getWoff2(body);
    downTotal = 0;
    fileTotal = fileList.length;
    done = function() {
      fileList.forEach(function(fontUrl) {
        var fontName;
        fontName = fontUrl.split('/').pop();
        return body = body.replace(fontUrl, './' + fontName);
      });
      fs.writeFileSync(path.join(outDir, 'font.css'), body, 'utf8');
      return console.log('download fonts success { %s/font.css }', outDir);
    };
    return fileList.forEach(function(fontUrl) {
      var fontName;
      fontName = fontUrl.split('/').pop();
      return request({
        url: fontUrl
      }).pipe(fs.createWriteStream(path.join(outDir, fontName))).on('close', function() {
        downTotal++;
        if (downTotal === fileTotal) {
          return done();
        }
      });
    });
  });
};
