// Generated by CoffeeScript 1.9.3

/**
 * 
 * @date 2015-11-12 15:47:32
 * @author vfasky <vfasky@gmail.com>
 * @link http://vfasky.com
 * @version $Id$
 */

(function() {
  var crypto;

  crypto = require('crypto');

  exports.md5 = function(text) {
    return crypto.createHash('md5').update(String(text)).digest('hex');
  };

}).call(this);
